// Decompiled with JetBrains decompiler
// Type: SwissArmyKnifeForMugen.Mugen10DB
// Assembly: SAKnifeWM, Version=1.0.8.0, Culture=neutral, PublicKeyToken=null
// MVID: 09478AD8-365C-4BF3-BEA1-B5785151259B
// Assembly location: C:\Users\ziddi\Downloads\Swiss Army Knife 1.1 Conversion\Swiss Army Knife 1.1 Conversion\SAKnifeWM.exe

namespace SwissArmyKnifeForMugen
{
  public class Mugen10DB : MugenAddrDatabase
  {
    public Mugen10DB()
    {
      this.MUGEN_POINTER_BASE_OFFSET = 5420044U;
      this.PAUSE_ADDR = 5421392U;
      this.CMD_CURRENT_INDEX_ADDR = 5417448U;
      this.CMD_NEXT_INDEX_ADDR = 5417452U;
      this.CMD_KEY_ADDR = 5416424U;
      this.DEMO_BASE_OFFSET = 71272U;
      this.MUGEN_ACTIVE_BASE_OFFSET = 71268U;
      this.SPEED_MODE_BASE_OFFSET = 74844U;
      this.SKIP_MODE_BASE_OFFSET = 69292U;
      this.DEBUG_MODE_BASE_OFFSET = 73800U;
      this.DEBUG_TARGET_BASE_OFFSET = 73792U;
      this.GAMETIME_BASE_OFFSET = 69288U;
      this.SCREEN_X_BASE_OFFSET = 46112U;
      this.SCREEN_Y_BASE_OFFSET = 46116U;
      this.ROUND_STATE_BASE_OFFSET = 71440U;
      this.ROUND_NO_BASE_OFFSET = 71396U;
      this.ROUND_TIME_BASE_OFFSET = 71460U;
      this.ROUND_NO_OF_MATCH_TIME_BASE_OFFSET = 2584U;
      this.TURNS_MODE_BASE_OFFSET = 2588U;
      this.TEAM_WIN_BASE_OFFSET = 71444U;
      this.TEAM_WIN_KO_BASE_OFFSET = 71448U;
      this.TEAM_1_WIN_COUNT_BASE_OFFSET = 71400U;
      this.TEAM_2_WIN_COUNT_BASE_OFFSET = 71404U;
      this.DRAW_GAME_COUNT_BASE_OFFSET = 71412U;
      this.PLAYER_1_BASE_OFFSET = 70196U;
      this.EXPLOD_LIST_BASE_OFFSET = 64688U;
      this.PAL_TIME_BASE_OFFSET = 45880U;
      this.PAL_GRAY_BASE_OFFSET = 45884U;
      this.PAL_R_BASE_OFFSET = 45888U;
      this.PAL_G_BASE_OFFSET = 45892U;
      this.PAL_B_BASE_OFFSET = 45896U;
      this.PAUSE_TIME_BASE_OFFSET = 48084U;
      this.SUPER_PAUSE_TIME_BASER_OFFSET = 48120U;
      this.OFFSET_EXPLOD_LIST_OFFSET = 264U;
      this.ANIM_ADDR_EXPLOD_OFFSET = 128U;
      this.ANIM_INDEX_EXPLOD_OFFSET = 12U;
      this.EXIST_EXPLOD_OFFSET = 0U;
      this.EXPLOD_ID_EXPLOD_OFFSET = 16U;
      this.EXPLOD_OWNER_ID_EXPLOD_OFFSET = 12U;
      this.PROJ_LIST_PROJ_BASE_OFFSET = 24U;
      this.PROJ_MAX_PROJ_BASE_OFFSET = 40U;
      this.OFFSET_PROJ_LIST_OFFSET = 736U;
      this.EXIST_PROJ_OFFSET = 4U;
      this.PROJ_ID_PROJ_OFFSET = 0U;
      this.PROJ_X_PROJ_OFFSET = 68U;
      this.PROJ_Y_PROJ_OFFSET = 72U;
      this.OFFSET_ANIM_LIST_OFFSET = 16U;
      this.ANIM_NO_ANIM_OFFSET = 12U;
      this.ANIM_INFO_ANIM_OFFSET = 16U;
      this.CLSN1_ADDR_ANIM_INFO_OFFSET = 40U;
      this.CLSN2_ADDR_ANIM_INFO_OFFSET = 44U;
      this.OFFSET_HITOVERRIDE_LIST_OFFSET = 20U;
      this.EXIST_HITOVERRIDE_OFFSET = 0U;
      this.ATTR_HITOVERRIDE_OFFSET = 4U;
      this.NUMTARGET_TARGET_ENTRY_OFFSET = 8U;
      this.TARGET_LIST_TARGET_ENTRY_OFFSET = 24U;
      this.OFFSET_TARGET_LIST_OFFSET = 28U;
      this.EXIST_PLAYER_OFFSET = 432U;
      this.PLAYER_ID_PLAYER_OFFSET = 4U;
      this.HELPER_ID_PLAYER_OFFSET = 5236U;
      this.PARENT_ID_PLAYER_OFFSET = 5240U;
      this.PROJ_BASE_PLAYER_OFFSET = 616U;
      this.STATE_OWNER_PLAYER_OFFSET = 3144U;
      this.STATE_NO_PLAYER_OFFSET = 3148U;
      this.PREV_STATE_NO_PLAYER_OFFSET = 3152U;
      this.PALNO_PLAYER_OFFSET = 5152U;
      this.ALIVE_PLAYER_OFFSET = 3712U;
      this.LIFE_PLAYER_OFFSET = 444U;
      this.POWER_PLAYER_OFFSET = 472U;
      this.DAMAGE_PLAYER_OFFSET = 4228U;
      this.CTRL_PLAYER_OFFSET = 3684U;
      this.STATE_TYPE_PLAYER_OFFSET = 3672U;
      this.MOVE_TYPE_PLAYER_OFFSET = 3676U;
      this.HIT_PAUSE_TIME_PLAYER_OFFSET = 3696U;
      this.MOVE_CONTACT_PLAYER_OFFSET = 3724U;
      this.MOVE_HIT_PLAYER_OFFSET = 3728U;
      this.ANIM_ADDR_PLAYER_OFFSET = 5144U;
      this.MUTEKI_PLAYER_OFFSET = 4180U;
      this.HITBY_1_PLAYER_OFFSET = 4184U;
      this.HITBY_2_PLAYER_OFFSET = 4188U;
      this.HITOVERRIDE_LIST_PLAYER_OFFSET = 4356U;
      this.TARGET_ENTRY_PLAYER_OFFSET = 620U;
      this.FALL_DAMAGE_PLAYER_OFFSET = 4300U;
      this.FACING_PLAYER_OFFSET = 488U;
      this.POS_X_PLAYER_OFFSET = 500U;
      this.POS_Y_PLAYER_OFFSET = 504U;
      this.VEL_X_PLAYER_OFFSET = 516U;
      this.VEL_Y_PLAYER_OFFSET = 520U;
      this.SYS_VAR_PLAYER_OFFSET = 4140U;
      this.SYS_FVAR_PLAYER_OFFSET = 4160U;
      this.VAR_PLAYER_OFFSET = 3740U;
      this.FVAR_PLAYER_OFFSET = 3980U;
      this.ACTIVE_PLAYER_OFFSET = 47720U;
      this.ASSERT_1_PLAYER_OFFSET = 47992U;
      this.PAUSE_MOVE_TIME_PLAYER_OFFSET = 552U;
      this.SUPER_PAUSE_MOVE_TIME_PLAYER_OFFSET = 556U;
      this.ATTACK_MUL_SET_PLAYER_OFFSET = 480U;
      this.DISPLAY_NAME_PLAYER_INFO_OFFSET = 48U;
      this.ANIM_LIST_REF1_PLAYER_INFO_OFFSET = 1080U;
      this.ANIM_LIST_REF2_PLAYER_INFO_OFFSET = 0U;
      this.ANIM_LIST_REF3_PLAYER_INFO_OFFSET = 28U;
    }
  }
}
